import CloseIconSvg from "./CloseIconSvg";
import DrawerIconSvg from "./DrawerIconSvg";
import CarrierShipIconSvg from "./CarrierShipIconSvg";
import MoreItemIconSvg from "./MoreItemIconSvg";
import BackIconSvg from "./BackIconSvg";
import ArrowIconSvg from "./ArrowIconSvg";
import SearchIconSvg from "./SearchIconSvg";
import DocumentIconSvg from "./DocumentIconSvg";
import MessageIconSvg from "./MessageIconSvg";
import MyAccountIconSvg from "./MyAccountIconSvg";
import LogOutIconSvg from "./LogOutIconSvg";
import AccountInfoIconSvg from "./AccountInfoIconSvg";
import PersonalProfileIconSvg from "./PersonalProfileIconSvg";
import SettingIconSvg from "./SettingIconSvg";
import CheckIconSvg from "./CheckIconSvg";
import LocationIconSvg from "./LocationIconSvg";
import PortIconSvg from "./PortIconSvg";
import EyeIconSvg from "./EyeIconSvg";
import LockIconSvg from "./LockIconSvg";
import CameraIconSvg from "./CameraIconSvg";
import CheckBoxIconSvg from "./CheckBoxIconSvg";
import PlusIconSvg from "./PlusIconSvg";
import CreditCardIconSvg from "./CreditCardIconSvg";
import PaypalIconSvg from "./PaypalIconSvg";
import AchIconSvg from "./AchIconSvg";
import HelpIconSvg from "./HelpIconSvg";
import InformationIconSvg from "./InformationIconSvg";

exports.BackIconSvg = BackIconSvg;
exports.CloseIconSvg = CloseIconSvg;
exports.DrawerIconSvg = DrawerIconSvg;
exports.CarrierShipIconSvg = CarrierShipIconSvg;
exports.MoreItemIconSvg = MoreItemIconSvg;
exports.ArrowIconSvg = ArrowIconSvg;
exports.SearchIconSvg = SearchIconSvg;
exports.DocumentIconSvg = DocumentIconSvg;
exports.MessageIconSvg = MessageIconSvg;
exports.MyAccountIconSvg = MyAccountIconSvg;
exports.LogOutIconSvg = LogOutIconSvg;
exports.AccountInfoIconSvg = AccountInfoIconSvg;
exports.PersonalProfileIconSvg = PersonalProfileIconSvg;
exports.SettingIconSvg = SettingIconSvg;
exports.CheckIconSvg = CheckIconSvg;
exports.LocationIconSvg = LocationIconSvg;
exports.PortIconSvg = PortIconSvg;
exports.EyeIconSvg = EyeIconSvg;
exports.LockIconSvg = LockIconSvg;
exports.CameraIconSvg = CameraIconSvg;
exports.CheckBoxIconSvg = CheckBoxIconSvg;
exports.PlusIconSvg = PlusIconSvg;
exports.CreditCardIconSvg = CreditCardIconSvg;
exports.PaypalIconSvg = PaypalIconSvg;
exports.AchIconSvg = AchIconSvg;
exports.HelpIconSvg = HelpIconSvg;
exports.InformationIconSvg = InformationIconSvg;
